export default {
  id: "elektriker",
  label: "Elektriker",
  co: "Voltz Elektro AS",
  loc: "Oslo",
  c: "#D4A039",
  cd: "#B8872F",
  cl: "#FBF5E6",
  tag: "Autorisert elektriker i Oslo — trygt, raskt og riktig",
  desc: "Voltz Elektro er et autorisert elektrikerfirma i Oslo med over 15 års erfaring. Vi utfører alt fra sikringsskapsoppgradering og elbillading til komplett elektrisk installasjon i nybygg. Forsikret arbeid med dokumentasjon og garanti.",
  heroSub: "Registrert i Elvirksomhetsregisteret. Forsikret arbeid med samsvarserklæring på alle oppdrag.",
  emergency: { active: true, text: "Akutt strømfeil? Vi har vakttelefon 24/7", phone: "400 00 000" },
  services: [
    { name: "Sikringsskap", desc: "Oppgradering fra skrusikring til automatsikringer med samsvarserklæring.", icon: "M4 4h16v16H4zM8 4v16M12 4v16M4 8h16M4 12h16M4 16h16" },
    { name: "Elbillading", desc: "Hjemmelader (Easee, Zaptec) med lastbalansering og korrekt dimensjonering.", icon: "M13 2L3 14h6l-1 6 10-12h-6l1-6z" },
    { name: "Elektrisk installasjon", desc: "Komplett installasjon for nybygg, tilbygg og renovering.", icon: "M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" },
    { name: "Smarthus", desc: "KNX, Hue og andre systemer for lys, varme og sikkerhet.", icon: "M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2V9zM9 22V12h6v10" },
    { name: "LED-belysning", desc: "Downlights, lister, utelys og effektbelysning med energibesparelse.", icon: "M9 18h6M12 2a7 7 0 00-4 12.7V17h8v-2.3A7 7 0 0012 2z" },
    { name: "Feilsøking", desc: "Termografering og avansert måleutstyr for rask feilretting.", icon: "M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2M21 12a9 9 0 11-18 0 9 9 0 0118 0z" },
    { name: "Periodisk kontroll", desc: "Lovpålagt kontroll etter FEL §9 med tilstandsrapport.", icon: "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 14l2 2 4-4" },
    { name: "Jordfeilvern", desc: "Montering og testing som beskytter mot brann og personskade.", icon: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4" },
    { name: "Varmekabel", desc: "Gulv, oppkjørsel og takrenner med Nexans og Ebeco.", icon: "M3 17c1-2 2-2 3 0s2 2 3 0 2-2 3 0 2 2 3 0M3 12c1-2 2-2 3 0s2 2 3 0 2-2 3 0M3 7c1-2 2-2 3 0s2 2 3 0 2-2 3 0" },
    { name: "Stikk og bryter", desc: "Nye stikkontakter, USB-uttak og dimmere. Elko, Gira, Schneider.", icon: "M5 3v18M19 3v18M5 12h14" },
    { name: "Hovedtavle næring", desc: "Prosjektering og bygging for næringsbygg etter NEK 400.", icon: "M4 4h16v4H4zM4 10h16v4H4zM4 16h16v4H4z" },
    { name: "El-tilsyn borettslag", desc: "Årlig kontroll og vedlikehold av fellesanlegg. Rammeavtaler.", icon: "M3 21h18M3 7v14M21 7v14M6 7V4M10 7V4M14 7V4M18 7V4" },
  ],
  st: { y: 15, p: 2400, t: 12, r: "4.9", reviews: 347 },
  rev: [
    { t: "Byttet hele sikringsskapet i leilighet fra 1972. Ryddig, dokumentert og ferdig på én dag. Anbefales!", n: "Thomas Bakken", r: "Boligeier, Nordstrand", stars: 5 },
    { t: "Easee-lader i garasjen med lastbalansering. Grundig jobb og god forklaring underveis.", n: "Silje Andersen", r: "Boligeier, Frogner", stars: 5 },
    { t: "Ringte etter jordfeil på kvelden. De kom innen 2 timer med termografering. Imponert.", n: "Markus Hagen", r: "Boligeier, Grünerløkka", stars: 5 },
    { t: "Totalrenovering — nytt anlegg fra bunn. Alt planlagt i detalj, overholdt tidsplan. Samsvarserklæring samme dag.", n: "Kristin Moe", r: "Boligeier, Majorstuen", stars: 5 },
    { t: "Vi bruker Voltz til 86 leiligheter i borettslaget. Effektivt med faste priser. Anbefales til andre styrer!", n: "Jan Eriksen", r: "Styreleder, Sinsen BRL", stars: 5 },
    { t: "KNX smarthus — lys, persienner og varme fra app. God opplæring. Fantastisk resultat.", n: "Lene Bakke", r: "Boligeier, Holmenkollen", stars: 5 },
  ],
  certs: [
    "Registrert i Elvirksomhetsregisteret (DSB)",
    "Autorisert installatørvirksomhet",
    "Forsikret gjennom IF Skadeforsikring",
    "Samsvarserklæring på alle oppdrag",
    "Mesterbrev i elektrikerfaget",
    "Godkjent kontrollvirksomhet (FEL §9)",
  ],
  areas: [
    "Oslo sentrum", "Frogner", "Majorstuen", "Grünerløkka", "St. Hanshaugen",
    "Nordstrand", "Lambertseter", "Sinsen", "Sagene", "Nydalen",
    "Blindern", "Ullern", "Røa", "Holmenkollen", "Bygdøy",
    "Aker Brygge", "Bjørvika", "Løren", "Bøler", "Manglerud",
  ],
  faq: [
    { q: "Hva koster det å bytte sikringsskap?", a: "Mellom 15 000–35 000 kr avhengig av størrelse og antall kurser. Vi gir alltid fast pris etter gratis befaring." },
    { q: "Hvor lang tid tar installasjon av elbillader?", a: "Standard 3–6 timer. Med ny kurs eller graving 1–2 dager. Fast pris etter befaring." },
    { q: "Trenger jeg å oppgradere sikringsskapet?", a: "Har du skrusikringer eller skap eldre enn 30 år, anbefaler vi oppgradering. Vi gjør gratis vurdering." },
    { q: "Hva er en samsvarserklæring?", a: "Lovpålagt dokument som bekrefter at arbeidet er utført etter NEK 400. Du får alltid dette fra oss." },
    { q: "Kommer dere på kveld og helg?", a: "Ja, vi har vakttelefon 24/7 for akutte strømfeil. 50% tillegg på kveld/helg." },
    { q: "Gir dere garanti?", a: "5 års garanti på alt arbeid etter håndverkertjenesteloven. Produktgaranti fra produsent i tillegg." },
  ],
  pricing: [
    { service: "Bytte sikringsskap", range: "15 000 – 35 000 kr" },
    { service: "Installere elbillader", range: "8 000 – 18 000 kr" },
    { service: "Stikkontakt / bryter", range: "1 200 – 3 500 kr" },
    { service: "LED downlights (10 stk)", range: "8 000 – 15 000 kr" },
    { service: "Feilsøking", range: "Fra 2 500 kr" },
    { service: "Periodisk kontroll", range: "3 500 – 8 000 kr" },
  ],
  process: [
    { n: "01", t: "Kontakt oss", d: "Ring, send melding eller fyll ut skjema." },
    { n: "02", t: "Gratis befaring", d: "Vi vurderer jobben og gir fast pris." },
    { n: "03", t: "Utførelse", d: "Autoriserte elektrikere utfører arbeidet." },
    { n: "04", t: "Dokumentasjon", d: "Samsvarserklæring og 5 års garanti." },
  ],
};
